# This is the default example Longboat site.yml playbook.
# Most recent version is available here:
# https://github.com/longboatio/longboat/blob/master/files/site.yml
#
# You should use this to set which hosts and groups that will get
# which roles applied. See the official Ansible docs for more information:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
---
- hosts: all
  roles:
    - longboat/hostname/v1
    - longboat/users/v1

# Setup UFW (firewall) on all hosts - IMPORTANT: Read the documentation first:
# https://github.com/longboatio/roles/tree/master/ufw/v1
#- hosts: all
#  roles:
#    - longboat/ufw/v1

# Install do-agent on hosts in group: digitalocean
#- hosts: digitalocean
#  roles:
#    - longboat/do-agent/v1

